#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "Chip8"
#define MEMORY_SIZE 4096
#define PROGRAM_LOAD_ADDRESS 0x200
#define WIDTH 64
#define HEIGHT 32
#define SCREEN_SCALER 10

#define TOTAL_DATA_REGISTERS 16
#define TOTAL_STACK_DEPTH 16
#define TOTAL_KEYS 16
#define CHARACTER_SET_LOAD_ADDRESS 0x00
#define DEFAULT_SPRITE_HEIGHT 5

#endif